FROM my-registry:55000/gen:ci-${GENERATOR_BUILD_NUMBER-10}
WORKDIR /vsdbg
RUN apt-get update && apt-get install -y --no-install-recommends unzip \
&& rm -rf /var/lib/apt/lists/* \
&& curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

EXPOSE 80/tcp

WORKDIR /app

ENTRYPOINT echo "Ready for debugging." && sleep infinity 