FROM microsoft/aspnetcore-build:2.0.0-preview1

RUN apt-get update && apt-get install -y unzip

WORKDIR /clrdbg

RUN curl -SL \
	https://raw.githubusercontent.com/Microsoft/MIEngine/getclrdbg-release/scripts/GetClrDbg.sh \
	--output GetClrDbg.sh \
    && chmod 700 GetClrDbg.sh \
    && ./GetClrDbg.sh -v latest -l . \
    && rm GetClrDbg.sh

EXPOSE 80/tcp

WORKDIR /app

COPY api.csproj .
RUN dotnet restore

COPY . .
RUN dotnet build

ENTRYPOINT echo "Ready for debugging." && sleep infinity 
