version: '3.1'

services:
 # mail:
 #   image: mailhog/mailhog
  #  ports:
  #    - "${PORT_MAILHOG-8025}:8025"
  debug:
    build:
      context: .
      dockerfile: Dockerfile.Code
    image: marekkacprzak/generator:debug
    ports:
      - ${PORT_DEBUGER-3000}:80
   # depends_on:
   #   - mail